import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloClientProvider from "./apollo-provider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloClientProvider>
          {/* Navbar */}
          <div className="w-full h-16 bg-gray-800 text-white flex items-center px-5">
            <Link href="/" className="text-lg font-semibold">
              GraphQL Blog App
            </Link>
            <div className="ml-auto">
              <Link href="/auth/login" className="mr-4 hover:underline">
                Login
              </Link>
              <Link href="/auth/register" className="hover:underline">
                Register
              </Link>
            </div>
          </div>
          {/* Main Content */}
          {children}
        </ApolloClientProvider>
      </body>
    </html>
  );
}
